---
AWSTemplateFormatVersion: 2010-09-09
Description: Storage Gateway
Parameters:
  FileShareName:
     Type: String
     Description: Name of the file share
  FolderName:
     Type: String
     Description: Name of the folder inside the bucket  
  ClientIP:
     Type: String
     Description: Client´s IP Address (w.x.y.z/32)
Resources:
  StorageGatewayFileShareRole:  
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: storagegateway.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: StorageGatewayProvider
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Action:
                  - s3:GetAccelerateConfiguration
                  - s3:GetBucketLocation
                  - s3:GetBucketVersioning
                  - s3:ListBucket
                  - s3:ListBucketVersions
                  - s3:ListBucketMultipartUploads
                Resource: arn:aws:s3:::s3bucket03721695533642
                Effect: Allow
              - Action:
                  - s3:AbortMultipartUpload
                  - s3:DeleteObject
                  - s3:DeleteObjectVersion
                  - s3:GetObject
                  - s3:GetObjectAcl
                  - s3:GetObjectVersion
                  - s3:ListMultipartUploadParts
                  - s3:PutObject
                  - s3:PutObjectAcl
                Resource: arn:aws:s3:::s3bucket03721695533642*
                Effect: Allow
  StorageGatewayNfsFileShare:
    Type: Custom::StorageGatewayNfsFileShare
    Properties:
      FileShareName: !Ref  FileShareName
      GatewayARN: arn:aws:storagegateway:us-east-1:721695533642:gateway/sgw-05BC526C
      Role: !GetAtt StorageGatewayFileShareRole.Arn
      LocationARN: !Join  [ "", ["arn:aws:s3:::s3bucket03721695533642","/",!Ref FolderName,"/"] ]
      DefaultStorageClass: S3_STANDARD
      VPCEndpointDNSName: vpce-0bee7ce3ebab84fc4-fq2qxvrt.s3.us-east-1.vpce.amazonaws.com
      BucketRegion: us-east-1
      Squash: NoSquash
      ClientList:
        - !Ref ClientIP
      ServiceToken: !Sub 'arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:cfn-storagegateway-provider'
