---
AWSTemplateFormatVersion: 2010-09-09
Description: Storage Gateway
Resources:
   BackupPortfolio:
       Type: AWS::ServiceCatalog::Portfolio
       Properties:
         DisplayName: emcalibackup
         ProviderName: emcali
         Description: "Portafolio de productos para Backup usando Storage Gateway"

   BackupFileShareProduct:
       Type: AWS::ServiceCatalog::CloudFormationProduct
       Properties:
         Name: "BackupFileShare"
         Owner: "emcali"
         ProvisioningArtifactParameters:
             - Name: v1.0
               Info: 
                  LoadTemplateFromURL:  "https://cfn-storagegateway-provider-deploy-721695533642.s3.amazonaws.com/templates/fileshare3.yaml"

   BackupFileSharePortfolioAssociation:
       Type: AWS::ServiceCatalog::PortfolioProductAssociation
       Properties:
         PortfolioId: !Ref BackupPortfolio
         ProductId: !Ref BackupFileShareProduct
    
Outputs:
   BackupPortfolioProductId: 
     Description: "Identificador del Portafolio de Backup"
     Value: !Ref BackupPortfolio
